### ISSUE TITLE
部署运行

### ISSUE THREAD

**Issue by zqzxz** [CCCpan/Gebaini#1]
感谢您的分享，麻烦发下部署运行脚本，谢谢

**Comment by CCCpan** [comment]
> 感谢您的分享，麻烦下配置运行脚本，谢谢

PaddleOCR(
    det_model_dir="./base-model/paddleocr_sfz_09333/det_db_inference/",
    cls_model_dir="./base-model/paddleocr_sfz_09333/ch_ppocr_mobile_v2.0_cls_slim_infer",
    rec_model_dir="./base-model/paddleocr_sfz_09333/ch_PP-OCRv3_rec_slim_infer",
    use_angle_cls=True,
    vis_font_path="./base-model/paddleocr_sfz_09333/chinese_cht.ttf",
    det_db_thresh=0.3,
    det_db_box_thresh=0.6
)


完整服务代码还在整理中，可以看paddle文档直接使用
